/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.61
 * Generated at: 2021-11-19 08:43:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.lifepic;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\">\r\n");
      out.write("\r\n");
      out.write("  <title>LifePic</title>\r\n");
      out.write("  <meta content=\"\" name=\"description\">\r\n");
      out.write("  <meta content=\"\" name=\"keywords\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Favicons -->\r\n");
      out.write("  <link href=\"");
      out.print(request.getContextPath());
      out.write("/assets/img/favicon.png\" rel=\"icon\">\r\n");
      out.write("  <link href=\"");
      out.print(request.getContextPath());
      out.write("/assets/img/apple-touch-icon.png\" rel=\"apple-touch-icon\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Google Fonts -->\r\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Vendor CSS Files -->\r\n");
      out.write("  <link href=\"");
      out.print(request.getContextPath());
      out.write("/assets/vendor/animate.css/animate.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"");
      out.print(request.getContextPath());
      out.write("/assets/vendor/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"");
      out.print(request.getContextPath());
      out.write("/assets/vendor/bootstrap-icons/bootstrap-icons.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"");
      out.print(request.getContextPath());
      out.write("/assets/vendor/swiper/swiper-bundle.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"");
      out.print(request.getContextPath());
      out.write("/assets/css/common.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <!-- Template Main CSS File -->\r\n");
      out.write("  <link href=\"");
      out.print(request.getContextPath());
      out.write("/assets/css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("  <script src=\"");
      out.print(request.getContextPath() );
      out.write("/assets/js/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  <!-- =======================================================\r\n");
      out.write("  * Template Name: EstateAgency - v4.5.0\r\n");
      out.write("  * Template URL: https://bootstrapmade.com/real-estate-agency-bootstrap-template/\r\n");
      out.write("  * Author: BootstrapMade.com\r\n");
      out.write("  * License: https://bootstrapmade.com/license/\r\n");
      out.write("  ======================================================== -->\r\n");
      out.write("</head>\r\n");
      out.write("<title>LifePic</title>\r\n");
      out.write("<style>\r\n");
      out.write("a {\r\n");
      out.write("    color: #333;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("input {\r\n");
      out.write("   \r\n");
      out.write("    text-rendering: auto;\r\n");
      out.write("    color: initial;\r\n");
      out.write("    letter-spacing: normal;\r\n");
      out.write("    word-spacing: normal;\r\n");
      out.write("    text-transform: none;\r\n");
      out.write("    text-indent: 0px;\r\n");
      out.write("    text-shadow: none;\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    text-align: start;\r\n");
      out.write("    -webkit-appearance: textfield;\r\n");
      out.write("    background-color: white;\r\n");
      out.write("    -webkit-rtl-ordering: logical;\r\n");
      out.write("    cursor: text;\r\n");
      out.write("    margin: 0em;\r\n");
      out.write("    font: 400 13.3333px Arial;\r\n");
      out.write("    padding: 1px 0px;\r\n");
      out.write("    border-width: 2px;\r\n");
      out.write("    border-style: inset;\r\n");
      out.write("    border-color: initial;\r\n");
      out.write("    border-image: initial;\r\n");
      out.write("}\r\n");
      out.write(".inner_login {\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    left: 50%;\r\n");
      out.write("    top: 50%;\r\n");
      out.write("    margin: -145px 0 0 -160px;\r\n");
      out.write("}\r\n");
      out.write(".login_tistory{\r\n");
      out.write("        position: relative;\r\n");
      out.write("        width: 320px;\r\n");
      out.write("        margin: 0 auto;\r\n");
      out.write("    }\r\n");
      out.write(".screen_out {\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    width: 0;\r\n");
      out.write("    height: 0;\r\n");
      out.write("    overflow: hidden;\r\n");
      out.write("    line-height: 0;\r\n");
      out.write("    text-indent: -9999px;    \r\n");
      out.write("}\r\n");
      out.write("body, button, input, select, td, textarea, th {\r\n");
      out.write("    font-size: 13px;\r\n");
      out.write("    line-height: 1.5;\r\n");
      out.write("    -webkit-font-smoothing: antialiased;\r\n");
      out.write("}    \r\n");
      out.write("fieldset, img {\r\n");
      out.write("    border: 0;\r\n");
      out.write("}\r\n");
      out.write(".login_tistory .box_login {\r\n");
      out.write("    margin: 35px 0 0;\r\n");
      out.write("    border: 1px solid #ddd;\r\n");
      out.write("    border-radius: 3px;\r\n");
      out.write("    background-color: #fff;\r\n");
      out.write("    box-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write(".login_tistory .inp_text {\r\n");
      out.write("    position: relative;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    padding: 18px 19px 19px;\r\n");
      out.write("    box-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write(".login_tistory .inp_text+.inp_text {\r\n");
      out.write("    border-top: 1px solid #ddd;\r\n");
      out.write("}\r\n");
      out.write(".inp_text input {\r\n");
      out.write("    display: block;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    height: 100%;\r\n");
      out.write("    font-size: 13px;\r\n");
      out.write("    color: #000;\r\n");
      out.write("    border: none;\r\n");
      out.write("    outline: 0;\r\n");
      out.write("    -webkit-appearance: none;\r\n");
      out.write("    background-color: transparent;\r\n");
      out.write("}\r\n");
      out.write(".input_login {\r\n");
      out.write("    margin: 20px 0 0;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    height: 48px;\r\n");
      out.write("    border-radius: 3px;\r\n");
      out.write("    font-size: 16px;\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    background-color: #000;\r\n");
      out.write("}\r\n");
      out.write(".login_append {\r\n");
      out.write("    overflow: hidden;\r\n");
      out.write("    padding: 15px 0 0;\r\n");
      out.write("}\r\n");
      out.write(".inp_chk {\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    position: relative;\r\n");
      out.write("    margin-bottom: -1px;\r\n");
      out.write("}\r\n");
      out.write(".login_append .inp_chk {\r\n");
      out.write("    float: left;\r\n");
      out.write("}\r\n");
      out.write(".inp_chk .inp_radio {\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    z-index: -1;\r\n");
      out.write("    top: 0;\r\n");
      out.write("    left: 0;\r\n");
      out.write("    width: 18px;\r\n");
      out.write("    height: 18px;\r\n");
      out.write("    border: 0;\r\n");
      out.write("}\r\n");
      out.write(".inp_chk .lab_g {\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    margin-right: 19px;\r\n");
      out.write("    color: #909090;\r\n");
      out.write("    font-size: 13px;\r\n");
      out.write("    line-height: 19px;\r\n");
      out.write("    vertical-align: top;\r\n");
      out.write("}\r\n");
      out.write(".inp_chk .ico_check {\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    width: 18px;\r\n");
      out.write("    height: 18px;\r\n");
      out.write("    margin: 1px 4px 0 0;\r\n");
      out.write("    background-position: -60px 0;\r\n");
      out.write("    color: #333;\r\n");
      out.write("}\r\n");
      out.write(".inp_chk .txt_lab {\r\n");
      out.write("    vertical-align: top;\r\n");
      out.write("}\r\n");
      out.write(".login_append .txt_find {\r\n");
      out.write("    float: right;\r\n");
      out.write("    color: #777;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<body>\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("   <!-- ======= Property Search Section ======= -->\r\n");
      out.write("  <!-- 상세검색 페이지 -->\r\n");
      out.write("\r\n");
      out.write("  <div class=\"click-closed\"></div>\r\n");
      out.write("  <!--/ Form Search Star /-->\r\n");
      out.write("  <div class=\"box-collapse\">\r\n");
      out.write("    <div class=\"title-box-d\">\r\n");
      out.write("     \r\n");
      out.write("      <h3 class=\"title-d\">상세검색</h3>\r\n");
      out.write("    </div>\r\n");
      out.write("    <span class=\"close-box-collapse right-boxed bi bi-x\"></span>\r\n");
      out.write("    <div class=\"box-collapse-wrap form\">\r\n");
      out.write("      <form class=\"form-a\">\r\n");
      out.write("        <!-- 행 추가 -->\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <!-- 컬럼 배치 -->\r\n");
      out.write("          <div class=\"col-md-12 mb-2\">\r\n");
      out.write("            <!-- 폼 그룹 배치 -->\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("              <label class=\"pb-2\" for=\"Type\">키워드</label>\r\n");
      out.write("              <!-- 텍스트 입력 폼 크기 조정 컨트롤러 배치 -->\r\n");
      out.write("              <input type=\"text\" class=\"form-control form-control-lg form-control-a\" placeholder=\"키워드/아티스트\">\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-6 mb-2\">\r\n");
      out.write("            <div class=\"form-group mt-3\">\r\n");
      out.write("              <!-- 상세검색 카테고리  -->\r\n");
      out.write("              <label class=\"pb-2\" for=\"Type\">카테고리</label>\r\n");
      out.write("              <select class=\"form-control form-select form-control-a\" id=\"Type\">\r\n");
      out.write("                <option>모든 카테고리</option>\r\n");
      out.write("                <option>추상</option>\r\n");
      out.write("                <option>동물/야생동물</option>\r\n");
      out.write("                <option>건물/랜드마크</option>\r\n");
      out.write("                <option>비즈니스</option>\r\n");
      out.write("                <option>유명인</option>\r\n");
      out.write("                <option>교육</option>\r\n");
      out.write("                <option>식음료</option>\r\n");
      out.write("                <option>산업</option>\r\n");
      out.write("                <option>일러스트</option>\r\n");
      out.write("              </select>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("               <!-- 칼럼 크기 -->\r\n");
      out.write("          <div class=\"col-md-6 mb-2\">\r\n");
      out.write("            <!-- 폼 그룹 배치 -->\r\n");
      out.write("            <div class=\"form-group mt-3\">\r\n");
      out.write("              <label class=\"pb-2\" for=\"city\">용도</label>\r\n");
      out.write("                       <!-- SELECT 폼 컨트롤러 배치 -->\r\n");
      out.write("              <select class=\"form-control form-select form-control-a\" id=\"city\">\r\n");
      out.write("                <option>Editorial</option>\r\n");
      out.write("                <option>not Editorial</option>\r\n");
      out.write("                <!-- <option>Arizona</option>\r\n");
      out.write("                <option>California</option>\r\n");
      out.write("                <option>Colorado</option> -->\r\n");
      out.write("              </select>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("               <!-- 칼럼 크기 -->\r\n");
      out.write("          <div class=\"col-md-6 mb-2\">\r\n");
      out.write("                     <!-- 폼 그룹 배치 -->\r\n");
      out.write("            <div class=\"form-group mt-3\">\r\n");
      out.write("              <label class=\"pb-2\" for=\"bedrooms\">이미지 크기</label>\r\n");
      out.write("                         <!-- SELECT 폼 컨트롤러 배치 -->\r\n");
      out.write("              <select class=\"form-control form-select form-control-a\" id=\"bedrooms\">\r\n");
      out.write("                <option>Inches-300DPI</option>\r\n");
      out.write("                <option>Inches-150DPI</option>\r\n");
      out.write("                <option>CM-300DPI</option>\r\n");
      out.write("                <option>CM-150DPI</option>\r\n");
      out.write("              </select>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("               <!-- 칼럼 크기 -->\r\n");
      out.write("          <div class=\"col-md-6 mb-2\">\r\n");
      out.write("                     <!-- 폼 그룹 배치 -->\r\n");
      out.write("            <div class=\"form-group mt-3\">\r\n");
      out.write("              <label class=\"pb-2\" for=\"garages\">이미지 형식</label>\r\n");
      out.write("                         <!-- SELECT 폼 컨트롤러 배치 -->\r\n");
      out.write("              <select class=\"form-control form-select form-control-a\" id=\"garages\">\r\n");
      out.write("                <option>모든 이미지</option>\r\n");
      out.write("                <option>사진</option>\r\n");
      out.write("                <option>백터</option>\r\n");
      out.write("                <option>일러스트</option>\r\n");
      out.write("                <!-- <option>04</option> -->\r\n");
      out.write("              </select>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- 컬럼 크기 -->\r\n");
      out.write("          <div class=\"col-md-6 mb-2\">\r\n");
      out.write("                     <!-- 폼 그룹 배치 -->\r\n");
      out.write("            <div class=\"form-group mt-3\">\r\n");
      out.write("              <label class=\"pb-2\" for=\"bathrooms\">방향</label>\r\n");
      out.write("                         <!-- SELECT 폼 컨트롤러 배치 -->\r\n");
      out.write("              <select class=\"form-control form-select form-control-a\" id=\"bathrooms\">\r\n");
      out.write("                <option>모든 방향</option>\r\n");
      out.write("                <option>가로</option>\r\n");
      out.write("                <option>세로</option>\r\n");
      out.write("                <!-- <option>03</option> -->\r\n");
      out.write("              </select>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("               <!-- 칼럼 크기 -->\r\n");
      out.write("          <div class=\"col-md-6 mb-2\">\r\n");
      out.write("                     <!-- 폼 그룹 배치 -->\r\n");
      out.write("            <div class=\"form-group mt-3\">\r\n");
      out.write("              <label class=\"pb-2\" for=\"price\">실사</label>\r\n");
      out.write("                         <!-- SELECT 폼 컨트롤러 배치 -->\r\n");
      out.write("              <select class=\"form-control form-select form-control-a\" id=\"price\">\r\n");
      out.write("                <option>모두표시</option>\r\n");
      out.write("                <option>실사만</option>\r\n");
      out.write("                <!-- <option>$100,000</option>\r\n");
      out.write("                <option>$150,000</option>\r\n");
      out.write("                <option>$200,000</option> -->\r\n");
      out.write("              </select>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- 칼럼 크기 -->\r\n");
      out.write("          <div class=\"col-md-12\">\r\n");
      out.write("            <!-- 폼 전송 속성 검색하기 버튼 생성 -->\r\n");
      out.write("            <button type=\"submit\" class=\"btn btn-b\">검색하기</button>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </form>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div><!-- End Property Search Section -->>\r\n");
      out.write("  \r\n");
      out.write("  <!-- ======= Header/Navbar ======= -->\r\n");
      out.write("  <nav class=\"navbar navbar-default navbar-trans navbar-expand-lg fixed-top\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <button class=\"navbar-toggler collapsed\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarDefault\" aria-controls=\"navbarDefault\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("        <span></span>\r\n");
      out.write("        <span></span>\r\n");
      out.write("        <span></span>\r\n");
      out.write("      </button>\r\n");
      out.write("      <!-- 최상단-->\r\n");
      out.write("      <div class=\"mobile-menu-wrap\">\r\n");
      out.write("        <div class=\"mobile-menu-scroll\">\r\n");
      out.write("            <ul class=\"util-menu\">\r\n");
      out.write("              <li><a href=\"login.jsp\">Login</a></li>\r\n");
      out.write("              <li><a href=\"join.jsp\">Join</a></li>\r\n");
      out.write("              <li><a href=\"#\">Sitemap</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div> <!--end최상단-->\r\n");
      out.write("      <!--로고-->\r\n");
      out.write("      <a class=\"navbar-brand text-brand\" href=\"index.jsp\">Life<span class=\"color-b\">Pic</span></a>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"navbar-collapse collapse justify-content-center\" id=\"navbarDefault\">\r\n");
      out.write("        <!--상단바 순서-->\r\n");
      out.write("        <ul class=\"navbar-nav\">\r\n");
      out.write("\r\n");
      out.write("          <li class=\"nav-item\">\r\n");
      out.write("            <a class=\"nav-link active\" href=\"index.jsp\">Home</a>\r\n");
      out.write("          </li>\r\n");
      out.write("\r\n");
      out.write("          \r\n");
      out.write("          <li class=\"nav-item\">\r\n");
      out.write("            <a class=\"nav-link \" href=\"property-grid.jsp\">BestPic</a>\r\n");
      out.write("          </li>\r\n");
      out.write("          \r\n");
      out.write("          <li class=\"nav-item\">\r\n");
      out.write("            <a class=\"nav-link \" href=\"blog-grid.jsp\">Gallery</a>\r\n");
      out.write("          </li>\r\n");
      out.write("         \r\n");
      out.write("          <li class=\"nav-item\">\r\n");
      out.write("            <a class=\"nav-link \" href=\"about.jsp\">About</a>\r\n");
      out.write("          </li>\r\n");
      out.write("          \r\n");
      out.write("          <li class=\"nav-item\">\r\n");
      out.write("            <a class=\"nav-link \" href=\"contact.jsp\">Contact</a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <!--드랍다운 메뉴-->\r\n");
      out.write("          <li class=\"nav-item dropdown\">\r\n");
      out.write("            <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\" role=\"button\" data-bs-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">Pages</a>\r\n");
      out.write("            <div class=\"dropdown-menu\">\r\n");
      out.write("              <a class=\"dropdown-item \" href=\"property-single.jsp\">상세페이지</a>\r\n");
      out.write("              <a class=\"dropdown-item \" href=\"Comment.jsp\">Commet</a>\r\n");
      out.write("              <a class=\"dropdown-item \" href=\"agents-grid.jsp\">Photographer</a>\r\n");
      out.write("              <a class=\"dropdown-item \" href=\"agent-single.jsp\">My Page</a>\r\n");
      out.write("            </div>\r\n");
      out.write("          </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <button type=\"button\" class=\"btn btn-b-n navbar-toggle-box navbar-toggle-box-collapse\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarTogglerDemo01\">\r\n");
      out.write("        <i class=\"bi bi-search\"></i>\r\n");
      out.write("      </button>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("  </nav><!-- End Header/Navbar -->\r\n");
      out.write("\r\n");
      out.write("<div class=\"inner_login\">\r\n");
      out.write("    <div class=\"login_tistory\">\r\n");
      out.write("\r\n");
      out.write("        <form method=\"post\" id=\"authForm\" action=\"login.do\">\r\n");
      out.write("            <input type=\"hidden\" name=\"redirectUrl\" value=\"\">\r\n");
      out.write("            <fieldset>\r\n");
      out.write("            <legend class=\"screen_out\">로그인 정보 입력폼</legend>\r\n");
      out.write("            <div class=\"box_login\">\r\n");
      out.write("                <div class=\"inp_text\">\r\n");
      out.write("                <label for=\"loginId\" class=\"screen_out\"></label>\r\n");
      out.write("                <input type=\"text\" id=\"loginId\" name=\"id\" placeholder=\"ID\" >\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"inp_text\">\r\n");
      out.write("                <label for=\"password\" class=\"screen_out\">비밀번호</label>\r\n");
      out.write("                <input type=\"password\" id=\"password\" name=\"password\" placeholder=\"Password\" >\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <input type=\"submit\" class=\"input_login\" value=\"로그인\">\r\n");
      out.write("            </fieldset>\r\n");
      out.write("        </form>\r\n");
      out.write("            <div class=\"login_append\">\r\n");
      out.write("                <div class=\"inp_chk\"> <!-- 체크시 checked 추가 -->\r\n");
      out.write("                <input type=\"checkbox\" id=\"keepLogin\" class=\"inp_radio\"  name=\"keepLogin\">\r\n");
      out.write("                <label for=\"keepLogin\" class=\"lab_g\">\r\n");
      out.write("        <span class=\"img_top ico_check\"></span>\r\n");
      out.write("        <span class=\"txt_lab\">로그인 상태 유지</span>\r\n");
      out.write("        </label>\r\n");
      out.write("                </div>\r\n");
      out.write("                <span class=\"txt_find\">\r\n");
      out.write("                <a href=\"/member/find/loginId\" class=\"link_find\">아이디</a>\r\n");
      out.write("                    / \r\n");
      out.write("                <a href=\"/member/find/password\" class=\"link_find\">비밀번호 찾기</a>\r\n");
      out.write("                </span>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("        \r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
